-- OBSOLETE: no longer needed and safe to ignore.
--
-- Version history originally wanted its own workspace_snapshots table, which
-- was never created on the live project and produced console 404s. The app
-- now stores version rows inside the existing workspace_state table, using
-- prefixed row ids like "ucc-default:snapshot:<timestamp>", so no extra
-- table, SQL, or migration is required.
--
-- This file is kept only as a record; running it is harmless but pointless.
-- If you previously created workspace_snapshots and want to remove it:
--   drop table if exists public.workspace_snapshots;
